Parameters:
  ExportName:
    Type: String
    Description: The name of the export for the Cognito Lambda Execution Role

Resources:
  CognitoLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "CognitoFullAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cognito-idp:AdminCreateUser"
                  - "cognito-idp:AdminInitiateAuth"
                  - "cognito-idp:ListUsers"
                  - "cognito-idp:AdminSetUserPassword"
                  - "cognito-idp:AdminGetUser"
                  - "cognito-idp:AdminUpdateUserAttributes"
                  - "cognito-idp:ListUserPools"
                  - "cognito-idp:DescribeUserPool"
                Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        

Outputs:
  RoleArn:
    Description: The ARN of the Cognito Lambda Execution Role
    Value: !GetAtt CognitoLambdaExecutionRole.Arn
  CognitoLambdaExecutionRoleName:
    Value: !Ref CognitoLambdaExecutionRole
    Export:
      Name: !Ref ExportName

