Resources:
  CognitoServiceAccount:
    Type: AWS::IAM::User
    Properties:
      UserName: CognitoServiceAccount
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess # Remove this if not needed
      Policies:
        - PolicyName: CognitoServiceAccountMinimalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/CognitoLambdaExecutionRole"
      Tags:
        - Key: "Environment"
          Value: "Development"

  CognitoServiceAccountRoleAttachment:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CognitoLambdaExecutionRole
      InstanceProfileName: CognitoServiceAccountProfile
