Parameters:
  ExportName:
    Type: String
    Description: The name of the exported Cognito Lambda Execution Role

Resources:
  CognitoServiceAccount:
    Type: AWS::IAM::User
    Properties:
      UserName: CognitoServiceAccount
      Policies:
        - PolicyName: CognitoServiceAccountMinimalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - !ImportValue
                    Ref: ExportName
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

