Parameters:
  RoleArn:
    Type: String
    Description: The ARN of the Foxy Lambda Execution Role
  EnvironmentName:
    Type: String
    Description: The name of the environment (e.g., dev, staging, production)
  SQSRoleArn:
    Type: String
    Description: The ARN of the Foxy Lambda SQS Role

Resources:
  FoxyServiceAccount:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${EnvironmentName}-FoxyServiceAccount"
      Policies:
        - PolicyName: FoxyServiceAccountMinimalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - !Ref RoleArn
                  - !Ref SQSRoleArn
              - Effect: Allow
                Action:
                  - "cloudformation:ListExports"
                Resource: "*"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

