Parameters:
  RoleArn:
    Type: String
    Description: The ARN of the Cognito Lambda Execution Role
  EnvironmentName:
    Type: String
    Description: The name of the environment (e.g., dev, staging, production)

Resources:
  CognitoServiceAccount:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${EnvironmentName}-CognitoServiceAccount"
      Policies:
        - PolicyName: CognitoServiceAccountMinimalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                  - "cloudformation:ListExports"
                Resource:
                  - !Ref RoleArn
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

