AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack to create DynamoDB tables and IAM roles for Foxy transaction processing.

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the environment (e.g., dev, staging, prod)

Resources:

  # DynamoDB Event Store Table
  TransactionEventLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "foxy_${EnvironmentName}_TransactionEventLog"
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # DynamoDB State View Table
  TransactionStateViewTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "foxy_${EnvironmentName}_TransactionStateView"
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: Status
          AttributeType: S
        - AttributeName: UpdatedAt
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1-Status-UpdatedAt
          KeySchema:
            - AttributeName: Status
              KeyType: HASH
            - AttributeName: UpdatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # New DynamoDB Table for Contact Discovery
  FoxyUserLookupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "foxy_${EnvironmentName}_UserLookup"
      AttributeDefinitions:
        - AttributeName: hashed_phone
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: hashed_phone
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # IAM Role for Application
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "foxy_${EnvironmentName}_AppRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "foxy_${EnvironmentName}_AppPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt TransactionEventLogTable.Arn
                  - !GetAtt TransactionStateViewTable.Arn
                  - !GetAtt FoxyUserLookupTable.Arn
    DeletionPolicy: Delete

  # IAM Role for Admin
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "foxy-${EnvironmentName}-AdminRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
    DeletionPolicy: Delete

  # IAM Role for Reporting
  ReportingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "foxy_${EnvironmentName}_ReportingRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: quicksight.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "foxy_${EnvironmentName}_ReportingPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource: !GetAtt TransactionStateViewTable.Arn
    DeletionPolicy: Delete

Outputs:

  EventLogTableName:
    Description: Name of the DynamoDB Event Log Table
    Value: !Ref TransactionEventLogTable

  StateViewTableName:
    Description: Name of the DynamoDB State View Table
    Value: !Ref TransactionStateViewTable

  UserLookupTableName:
    Description: Name of the DynamoDB User Lookup Table
    Value: !Ref FoxyUserLookupTable

  AppRoleARN:
    Description: ARN of the Application IAM Role
    Value: !GetAtt AppRole.Arn

  AdminRoleARN:
    Description: ARN of the Admin IAM Role
    Value: !GetAtt AdminRole.Arn

  ReportingRoleARN:
    Description: ARN of the Reporting IAM Role
    Value: !GetAtt ReportingRole.Arn

