AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Stack for Observing Key Rotation in Foxy"

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the environment (e.g., dev, staging, prod)
  KeyRotationRoleArn:
    Type: String
    Description: ARN of the IAM role for Lambda execution.
  UserPoolId:
    Type: String
    Description: The ID of the Cognito User Pool.

Resources:

  # 1️⃣ Lambda Function for Key Rotation
  KeyRotationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "foxy-${EnvironmentName}-KeyRotationLambda"
      Handler: rotate_key_lambda.lambda_handler
      Role: !Ref KeyRotationRoleArn
      Runtime: python3.9
      Timeout: 10
      MemorySize: 128
      Code:
        S3Bucket: !Sub "foxy-${EnvironmentName}-lambda-deployments-${AWS::AccountId}"
        S3Key: lambda/function.zip
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName

  # 2️⃣ Lambda Execution Permissions
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KeyRotationLambda
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}"

  # 3️⃣ CloudWatch Log Group for Lambda Logs
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/foxy-${EnvironmentName}-KeyRotation" 
      RetentionInDays: 90

  # 4️⃣ CloudWatch Metric Filter for Key Rotation Events
  KeyRotationMetricFilter:
    Type: AWS::Logs::MetricFilter
    DependsOn: LambdaLogGroup 
    Properties:
      LogGroupName: !Ref LambdaLogGroup
      FilterPattern: '{ $.event = "DID Key Rotation" }'
      MetricTransformations:
        - MetricNamespace: "FoxySecurity"
          MetricName: "DidKeyRotationCount"
          MetricValue: "1"

  # 5️⃣ CloudWatch Alarm for Missing Key Rotation
  KeyRotationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "foxy-${EnvironmentName}-DIDKeyRotationMissing"
      MetricName: "DidKeyRotationCount"
      Namespace: "FoxySecurity"
      Statistic: "Sum"
      Period: 86400 # 1 day
      EvaluationPeriods: 90 # Trigger if no rotation in 90 days
      Threshold: 1
      ComparisonOperator: "LessThanThreshold"
      AlarmActions:
        - !Ref SecurityNotificationsTopic

  # 6️⃣ SNS Topic for Key Rotation Alerts
  SecurityNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "Foxy-${EnvironmentName}-SecurityNotifications"
      TopicName: !Sub "foxy-${EnvironmentName}-SecurityNotifications"

  # 7️⃣ Subscribe SNS to Lambda
  SecurityLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SecurityNotificationsTopic
      Protocol: lambda
      Endpoint: !GetAtt SecurityNotificationLambda.Arn

  # 8️⃣ Allow SNS to invoke the Lambda function
  SNSInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SecurityNotificationLambda
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref SecurityNotificationsTopic

  # 9️⃣ Lambda Function to Process SNS and Forward via SES
  SecurityNotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "foxy-${EnvironmentName}-SecurityNotificationLambda"
      Handler: lambda_function.lambda_handler
      Role: !Ref KeyRotationRoleArn
      Runtime: python3.9
      Timeout: 10
      MemorySize: 128
      Code:
        S3Bucket: !Sub "foxy-${EnvironmentName}-lambda-deployments-${AWS::AccountId}"
        S3Key: lambda/sns_to_ses.zip
      Environment:
        Variables:
          SES_RECIPIENT: "foxy@getfoxy.app"
          SES_SENDER: "admin@getfoxy.app"

  KeyRotationDashboard:
    Type: AWS::CloudWatch::Dashboard
    DependsOn:
      - KeyRotationAlarm 
    Properties:
      DashboardName: !Sub "foxy-${EnvironmentName}-KeyRotation"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 6,
              "height": 3,
              "properties": {
                "metrics": [
                  [ "FoxySecurity", "DidKeyRotationCount" ]
                ],
                "region": "${AWS::Region}",
                "view": "timeSeries",
                "period": 86400,
                "stat": "Sum",
                "yAxis": {
                  "left": {
                    "label": "Rotations",
                    "showUnits": false
                  }
                },
                "title": "DID Key Rotations"
              }
            },
            {
              "type": "text",
              "x": 0,
              "y": 4,
              "width": 6,
              "height": 3,
              "properties": {
                "markdown": "## Key Rotation Status\nThis dashboard tracks key rotations. Alerts will be sent if rotations stop for more than 3 days."
              }
            },
            {
              "type": "alarm",
              "x": 6,
              "y": 0,
              "width": 6,
              "height": 3,
              "properties": {
                "title": "Key Rotation Alerts",
                "region": "${AWS::Region}",
                "alarms": [
                  "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm/foxy-${EnvironmentName}-DIDKeyRotationMissing"
                ]
              }
            }
          ]
        }

  # 🔟 EventBridge Rule to Trigger Key Rotation Every 90 Days
  KeyRotationSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(90 days)" 
      Targets:
        - Arn: !GetAtt KeyRotationLambda.Arn
          Id: "KeyRotationTarget"

  # 🔹 Give EventBridge Permission to Invoke Lambda
  KeyRotationLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: KeyRotationLambda
    Properties:
      FunctionName: !Ref KeyRotationLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt KeyRotationSchedule.Arn

Outputs:

  LambdaFunctionName:
    Description: "Name of the Key Rotation Lambda function"
    Value: !Ref KeyRotationLambda

  SecurityNotificationLambdaFunctionName:
    Description: "Name of the Security Notification Lambda function"
    Value: !Ref SecurityNotificationLambda

  LambdaFunctionArn:
    Description: "ARN of the Key Rotation Lambda function"
    Value: !GetAtt KeyRotationLambda.Arn

  LogGroup:
    Description: "CloudWatch Log Group for Key Rotation"
    Value: !Ref LambdaLogGroup

  SNSAlertTopic:
    Description: "SNS Topic for Key Rotation Alerts"
    Value: !Ref SecurityNotificationsTopic

  DashboardURL:
    Description: "CloudWatch Dashboard for Key Rotation"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home#dashboards:name=${KeyRotationDashboard}"
