AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation stack to create SQS queues and IAM roles for Foxy transaction processing.

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the environment (e.g., dev, staging, prod)

Resources:

  # Dead Letter Queues
  TransactionBroadcastDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub Foxy-${EnvironmentName}-TransactionBroadcastDLQ

  # Main Queues with DLQ Redrive Policy
  TransactionBroadcastQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub Foxy-${EnvironmentName}-TransactionBroadcastQueue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransactionBroadcastDLQ.Arn
        maxReceiveCount: 5

Outputs:

  BroadcastQueueURL:
    Description: "URL of the Transaction Broadcast Queue"
    Value: !Ref TransactionBroadcastQueue

  BroadcastDLQURL:
    Description: "URL of the Transaction Broadcast DLQ"
    Value: !Ref TransactionBroadcastDLQ
    
  TransactionBroadcastQueueArn:
    Description: ARN of the Transaction Broadcast Queue
    Value: !GetAtt TransactionBroadcastQueue.Arn
    Export:
      Name: !Sub "${EnvironmentName}-TransactionBroadcastQueueArn"
    
