AWSTemplateFormatVersion: '2010-09-09'
Description: Foxy Secrets Manager Setup for Private Key Derivation

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the environment (e.g., dev, staging, prod)


Resources:
  # Randomly generated server root key (for HMAC derivation)
  FoxyRootKeyV1:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub foxy/${EnvironmentName}/keys/v1
      Description: Server root key for deriving backup AES keys (v1)
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: "server_root_key"
        PasswordLength: 44
        ExcludeCharacters: "\"@/\\"
        RequireEachIncludedType: true
        ExcludePunctuation: true
        IncludeSpace: false
      Tags:
        - Key: Project
          Value: Foxy
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: WalletBackupEncryption

Outputs:
  FoxyRootKeyV1Arn:
    Description: ARN of the Foxy Root Key v1 Secret
    Value: !Ref FoxyRootKeyV1
    Export:
      Name: !Sub Foxy-${EnvironmentName}-RootKeyV1-SecretArn
